server: 
  port: 9002

ApplicationType: SPRING
UserName:  ASIMA

spring: 
  application: 
    name: STOCKS-SERVICE-PROD
 
eureka:
   client:

      preferedSameZone: true
      registerWithEureka: true
      fetchRegistry: true
      region: us-east-2
      #availabilityZones:
       #  us-east-2: us-east-2a, us-east-2b, us-east-2c
      serviceUrl:
       defaultZone: http://ec2-3-133-195-91.us-east-2.compute.amazonaws.com:8761/eureka/, http://ec2-18-189-46-111.us-east-2.compute.amazonaws.com:8761/eureka/,http://ec2-3-134-69-95.us-east-2.compute.amazonaws.com:8761/eureka/
      #serviceUrl:
       #defaultZone: http://ec2-3-133-195-91.us-east-2.compute.amazonaws.com:8761/eureka/
 
  # instance: 
  #    metadataMap.zone: us-east-2c 
      
   
db-service:
  ribbon:
      NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
      #listOfServers: ec2-3-133-195-91.us-east-2.compute.amazonaws.com:8300
      listOfServers: http://ec2-3-133-195-91.us-east-2.compute.amazonaws.com:8300,http://ec2-18-189-46-111.us-east-2.compute.amazonaws.com:8300, http://ec2-3-134-69-95.us-east-2.compute.amazonaws.com:8300
 
    
