server: 
  port: 8761
  enable-self-preservation: false
spring: 
  application: 
    name: EUREKA-SERVICE-PROD
ApplicationType: SPRING
UserName:  ASIMA
   

eureka:
   datacenter: cloud
   client:
      registerWithEureka: false
      fetchRegistry: false
      region: us-east-2
      preferedSameZone: true
      #availabilityZones:
      #   us-east-2: us-east-2a, us-east-2b, us-east-2c
      serviceUrl:
         
        # us-east-2a: http://ec2-18-189-46-111.us-east-2.compute.amazonaws.com:8761/eureka/
        # us-east-2b: http://ec2-3-133-195-91.us-east-2.compute.amazonaws.com:8761/eureka/
        # us-east-2c: http://ec2-3-134-69-95.us-east-2.compute.amazonaws.com:8761/eureka/
         defaultZone: http://ec2-3-133-195-91.us-east-2.compute.amazonaws.com:8761/eureka/,http://ec2-18-189-46-111.us-east-2.compute.amazonaws.com:8761/eureka/, http://ec2-3-134-69-95.us-east-2.compute.amazonaws.com:8761/eureka/
        
       
  # instance:
   #   metadataMap.zone: us-east-2c
      #hostname:0.0.0.0
      #hostname:192.168.0.195
     # hostname:localhost     
     # hostname:3.133.195.91
     # prefer-ip-address:true
logging:
   level:
      com:
         netflix:
            eureka: OFF
            discovery: OFF
    
    

#zuul:
#Service will be mapped under the /api URI
#   routes:
 #     db-service:  
  #       path: /db-service/**
   #      url: http://ec2-18-189-46-111.us-east-2.compute.amazonaws.com:8300/,http://ec2-3-133-195-91.us-east-2.compute.amazonaws.com:8300/,http://ec2-3-134-69-95.us-east-2.compute.amazonaws.com:8300/
       
    #  stock-service:
     #    path: /stock-service/**
      #   url: http://ec2-18-189-46-111.us-east-2.compute.amazonaws.com:9002/,http://ec2-3-133-195-91.us-east-2.compute.amazonaws.com:9002/,http://ec2-3-134-69-95.us-east-2.compute.amazonaws.com:9002/
      
zuul:
  routes:
    db-service:
      path: /db-service/**
      serviceId: db-service
    stock-service:
      path: /stock-service/**
      serviceId: stock-service
#ribbon:
#  eureka:
#    enabled: false

db-service:
  ribbon:
    listOfServers: http://ec2-3-133-195-91.us-east-2.compute.amazonaws.com:8300/,http://ec2-18-189-46-111.us-east-2.compute.amazonaws.com:8300/, http://ec2-3-134-69-95.us-east-2.compute.amazonaws.com:8300/
stock-service:
  ribbon:
    listOfServers: http://ec2-3-133-195-91.us-east-2.compute.amazonaws.com:9002/,http://ec2-18-189-46-111.us-east-2.compute.amazonaws.com:9002/, http://ec2-3-134-69-95.us-east-2.compute.amazonaws.com:9002/
 